#pragma once

#ifdef ENABLE_R4_MODE

#define NTR_CMD_ID_GAME_R4_DUMMY_READ       0x00
#define NTR_CMD_ID_GAME_R4_GET_CARD_INFO    0xB0
#define NTR_CMD_ID_GAME_R4_START_SAVE_READ  0xB2
#define NTR_CMD_ID_GAME_R4_GET_SAVE_DATA    0xB3
#define NTR_CMD_ID_GAME_R4_SEND_MAP         0xB4
#define NTR_CMD_ID_GAME_R4_START_ROM_READ   0xB6
#define NTR_CMD_ID_GAME_R4_START_SD_READ    0xB9
#define NTR_CMD_ID_GAME_R4_GET_SD_DATA      0xBA
#define NTR_CMD_ID_GAME_R4_START_SD_WRITE   0xBB
#define NTR_CMD_ID_GAME_R4_GET_WRITE_STAT   0xBC
#define NTR_CMD_ID_GAME_R4_START_SAVE_WRITE 0xBD
#define NTR_CMD_ID_GAME_R4_GET_SAVE_STAT    0xBE

#endif
